import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "@/components/NavbarWrapper";
import FooterWrapper from "@/components/FooterWrapper";
import AOSWrapper from "@/components/AOSWrapper";

// const geistSans = Poppins({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Poppins({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400','700'],
  variable: '--font-poppins',
  display: 'swap'
});

export const metadata: Metadata = {
  title: "jointventureassets.com",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <AOSWrapper />
        <NavbarWrapper />
          {children}
        <FooterWrapper />
      </body>
    </html>
  );
}
